name: Gardez Streamlit éveillé

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Application Ping Streamlit
        run: curl -L "https://medcodex-v2-3n7bazwmm37wt35cx5pvu.streamlit.app/" > /dev/null
